name: .NET CI

on:
  push:
    paths:
      - "03-dotnet-ci/**"
  pull_request:
    paths:
      - "03-dotnet-ci/**"
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore 03-dotnet-ci/DotnetApp.sln

      - name: Build
        run: dotnet build 03-dotnet-ci/DotnetApp.sln --configuration Release --no-restore

      - name: Run Tests with Console Output and TRX
        run: |
          dotnet test 03-dotnet-ci/DotnetApp.sln \
            --no-build \
            --configuration Release \
            --logger "console;verbosity=detailed;ForceConsoleOut=true" \
            --logger "trx;LogFileName=TestResults.trx"

      - name: Upload Test Results Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-test-results
          path: 03-dotnet-ci/DotnetApp.Tests/TestResults/TestResults.trx