name: GitHub Secrets

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:  
      - name: Print Secret
        run: |
            echo "MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY  }}"
            echo "i_dont_exist: ${{ secrets.i_dont_exist  }}"
            
      - name: Print Secret as an environment variable
        run: |
            echo "MY_SECRET_KEY: $MY_SECRET_KEY"
        env:
            MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}