name: GitHub Environments

on:
  workflow_dispatch:

jobs:
  deployment:
    
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: https://github.com
      
      
    steps:
      - name: 'Print secret from environment'
        run: |
            echo "MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}"
